package vanguard;

import android.util.Log;
import com.google.cloud.translate.v3.LocationName;
import com.google.cloud.translate.v3.TranslateTextRequest;
import com.google.cloud.translate.v3.TranslateTextResponse;
import com.google.cloud.translate.v3.Translation;
import com.google.cloud.translate.v3.TranslationServiceClient;

import java.io.IOException;

/**
 * GlobalTranslationService uses Google Cloud Translation API v3 to localize
 * emergency alerts from English into the user's device locale in real-time.
 *
 * Requires:
 *   - GOOGLE_CLOUD_PROJECT env var set to your GCP project ID.
 *   - Application Default Credentials configured (gcloud auth application-default login).
 *   - cloud-translate dependency in build.gradle:
 *       implementation 'com.google.cloud:google-cloud-translate:2.43.0'
 */
public class GlobalTranslationService {

    private static final String TAG = "GlobalTranslation";

    /** BCP-47 language tag for the target locale, e.g. "es", "ja", "fr", "hi". */
    private final String targetLanguageCode;

    /** GCP project ID, read from env for security. */
    private final String projectId;

    public GlobalTranslationService(String targetLanguageCode) {
        this.targetLanguageCode = targetLanguageCode;
        this.projectId = System.getenv("GOOGLE_CLOUD_PROJECT");
        if (projectId == null || projectId.isEmpty()) {
            Log.e(TAG, "GOOGLE_CLOUD_PROJECT env var not set. Translation will fall back to raw text.");
        }
        Log.i(TAG, "Translation Layer initialized → target locale: " + targetLanguageCode);
    }

    /**
     * Translates a raw English alert string into the target locale using
     * Google Cloud Translation API v3.
     *
     * Falls back to the original {@code rawAlert} if translation fails,
     * so the system never silently drops emergency information.
     *
     * @param rawAlert The English text generated by SentinelProcessor or GDC backend.
     * @return The translated string, or the original text on failure.
     */
    public String localizeAlert(String rawAlert) {
        // Skip translation if already in English or no project configured
        if (targetLanguageCode.equalsIgnoreCase("en")
                || targetLanguageCode.startsWith("en-")
                || projectId == null
                || projectId.isEmpty()) {
            return rawAlert;
        }

        try (TranslationServiceClient client = TranslationServiceClient.create()) {
            LocationName parent = LocationName.of(projectId, "global");

            TranslateTextRequest request = TranslateTextRequest.newBuilder()
                    .setParent(parent.toString())
                    .setMimeType("text/plain")
                    .setSourceLanguageCode("en")
                    .setTargetLanguageCode(targetLanguageCode)
                    .addContents(rawAlert)
                    .build();

            TranslateTextResponse response = client.translateText(request);

            if (response.getTranslationsCount() > 0) {
                Translation translation = response.getTranslations(0);
                String translated = translation.getTranslatedText();
                Log.i(TAG, "[TRANSLATE] " + targetLanguageCode + " → \"" + translated + "\"");
                return translated;
            }

        } catch (IOException e) {
            Log.e(TAG, "Translation API call failed: " + e.getMessage() + ". Falling back to English.");
        }

        // Safe fallback — never drop the alert
        return rawAlert;
    }

    /**
     * Convenience method used by AccessibilityLayer to translate and immediately
     * speak the alert via the GeminiVoiceAssistant.
     *
     * @param rawAlert   English alert text from SentinelProcessor.
     * @param assistant  The active GeminiVoiceAssistant instance.
     */
    public void translateAndSpeak(String rawAlert, GeminiVoiceAssistant assistant) {
        String localized = localizeAlert(rawAlert);
        assistant.speakInstruction(localized);
    }
}
